server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT
    username: root
    password: 301268
    type: com.alibaba.druid.pool.DruidDataSource
  data:
     redis:
      host: 127.0.0.1  #redis服务器地址
      port: 6379 #redis服务器连接端口
      password: #redis服务器连接密码(默认为空)
      database: 0 #redis数据库索引
      timeout: 1000  #连接超时时间
      jedis:
         pool:
           max-active: 200 #连接池最大连接数
           max-idle: 10 #连接池中的最大空闲连接
           min-idle: 0 #连接池中的最小空闲连接
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl