spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admininform?serverTimezone=UTC
    username: root
    password: 301268
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
